apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${IMAGE}
spec:
  template:
    metadata:
      labels:
        app: ${IMAGE}
    spec:
      containers:
      - name: ${IMAGE}
        image: marceloquadros/${IMAGE}:${VERSION}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
