spring:
  application:
    name: application-name
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 0.2
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}

server:
  port: ${SERVER_PORT:8080}

